[phases.setup]
nixPkgs = ['deno_2']

[phases.install]
cmds = [
    'deno task install'
]

[phases.build]
cmds = [
    'deno task build'
]

[start]
cmd = 'deno task start'

[nixpacks]
start-phase = "start"