[phases.setup]
nixPkgs = ['nodejs']

[phases.install]
cmds = [
    'npm install --production',
    'npm install -D tsconfig-paths'
]

[phases.build]
cmds = [
    'npm run build'
]

[start]
cmd = 'npm start'

[meta]
expose = '3000'